const $ = (selector) => document.querySelector(selector);
const escape = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons = {grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',folder:'M3 7V5h7l2 2h9v13H3z',activity:'M2 12h5l3-8 4 16 3-8h5',box:'m12 2 9 5v10l-9 5-9-5V7z M3 7l9 5 9-5 M12 12v10',plus:'M12 5v14 M5 12h14',arrow:'M5 12h14 M14 7l5 5-5 5',check:'m5 12 4 4L19 6',clock:'M12 8v5l3 2 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',branch:'M6 3v12a4 4 0 0 0 8 0V9 M6 6h0 M14 5v0',agent:'M7 8h10v10H7z M12 4v4 M4 12h3 M17 12h3 M10 12h0 M14 12h0',code:'m8 6-6 6 6 6 M16 6l6 6-6 6 M14 3l-4 18'};
const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name] || icons.box}"/></svg>`;
document.querySelectorAll('[data-icon]').forEach(el => {el.innerHTML = icon(el.dataset.icon);});
const terminal = new Set(['SUCCEEDED','FAILED','CANCELLED','BLOCKED','HUMAN_REVIEW_REQUIRED']);
const stateNames = {READY:'就绪',CREATED:'已创建',PLANNING:'需求规划',CONTRACTING:'建立契约',SCHEDULING:'任务调度',QUEUED:'等待执行',RUNNING:'运行中',REVIEWING:'审查中',VERIFYING:'验证中',REPAIRING:'修复中',INTEGRATING:'集成中',FINAL_VERIFY:'最终验证',PAUSED:'已暂停',SUCCEEDED:'已完成',FAILED:'失败',CANCELLED:'已取消',BLOCKED:'依赖阻塞',HUMAN_REVIEW_REQUIRED:'需要处理',SUBMITTED:'已提交'};
const badge = state => `<span class="badge ${state==='SUCCEEDED'||state==='passed'?'good':state==='FAILED'||state==='failed'?'bad':state==='HUMAN_REVIEW_REQUIRED'||state==='PAUSED'?'warn':!terminal.has(state)&&state!=='READY'?'live':''}">${escape(stateNames[state]||state)}</span>`;
const time = value => value ? new Date(value).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}) : '—';
const short = value => value ? value.slice(0,8) : '—';
const duration = ms => ms == null ? '—' : ms<1000 ? `${ms} ms` : `${(ms/1000).toFixed(1)} s`;
const empty = (title,description,action='') => `<div class="empty">${icon('folder')}<strong>${title}</strong><p>${description}</p>${action}</div>`;
const button = (action,text,primary=false,extra='') => `<button class="button ${primary?'primary':''}" data-action="${action}" ${extra}>${text}</button>`;
const panels = (title,body,extra='') => `<section class="panel"><div class="panel-heading"><h3>${title}</h3>${extra}</div>${body}</section>`;
let projects=[], runs=[], health={}, currentRun=null, currentProject=null, activeTab='overview', selectedTask=null, eventSource=null, liveEvents=[], refreshTimer=null, routeVersion=0;

async function api(path, body) {
  const response = await fetch('/api'+path, body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
  if(!response.ok){const error = await response.json().catch(()=>({detail:response.statusText}));throw new Error(typeof error.detail==='string'?error.detail:JSON.stringify(error.detail));}
  return response.json();
}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function heading(title,description,actions='',eyebrow='WORKSPACE OVERVIEW') {return `<div class="page-heading"><div><span class="eyebrow">${eyebrow}</span><h1>${escape(title)}</h1><p>${escape(description)}</p></div><div class="actions">${actions}</div></div>`;}
function metrics(items){return `<div class="metrics">${items.map(([label,value,note,ic])=>`<div class="metric"><div class="metric-top">${label}${icon(ic||'activity')}</div><div class="metric-value">${escape(value)}</div><div class="metric-note">${escape(note)}</div></div>`).join('')}</div>`;}
function projectRows(list){return list.map(project=>{const last = runs.find(r=>r.project_id===project.id);return `<a class="project-row" href="#project/${project.id}"><span class="project-icon">${icon('folder')}</span><div><div class="project-title">${escape(project.name)}</div><div class="project-description">Python · ${project.provider==='fixture'?'内置验收示例':'模型开发'} · ${time(project.created_at)}</div></div><div class="row-end">${badge(last?.state||'READY')}${icon('arrow')}</div></a>`;}).join('');}
function runTable(list){if(!list.length)return empty('尚无运行记录','创建项目并描述需求，开始第一次工程运行。');return `<div class="table-wrap"><table><thead><tr><th>运行 / 需求</th><th>状态</th><th>修复次数</th><th>耗时</th><th>开始时间</th></tr></thead><tbody>${list.map(run=>`<tr class="clickable" data-route="run/${run.id}"><td><strong>${escape(run.request.requirement.slice(0,46))}</strong><div class="mono muted" style="margin-top:6px">${run.id}</div></td><td>${badge(run.state)}</td><td>${run.metrics.repair_count}</td><td>${duration(run.metrics.duration_ms)}</td><td>${time(run.created_at)}</td></tr>`).join('')}</tbody></table></div>`;}
function dashboard(){const active=runs.filter(r=>!terminal.has(r.state));const success=runs.filter(r=>r.state==='SUCCEEDED');return heading('工程工作台','从一个需求开始，让工程过程清晰可见。',button('new-project',icon('plus')+' 创建项目',true))+`<section class="welcome"><div><span class="eyebrow">BUILD WITH CONFIDENCE</span><h2>让每一次交付，都有据可依。</h2><p>统一契约下的多 Agent 协作。从任务规划、并行开发到测试修复，<br>在一个工作空间里，追踪代码如何成为可验证的工程产物。</p></div>${button('demo','体验完整验收流程 '+icon('arrow'))}</section>`+metrics([['项目总数',projects.length,'当前工作空间','folder'],['正在运行',active.length,'独立任务，隔离执行','activity'],['成功交付',success.length,'已通过最终验证','check'],['自动修复',runs.reduce((n,r)=>n+r.metrics.repair_count,0),'有证据的有限重试','branch']])+`<div class="columns"><div>${panels('我的项目 <span class="count">'+projects.length+'</span>',projects.length?projectRows(projects.slice(0,4)):empty('你的第一个项目，从这里开始','创建新项目，或导入已有 Git 仓库。每次运行都会留下完整的工程记录。',button('new-project','创建项目',true)), '<a class="text-link" href="#projects">查看全部 →</a>')}</div><div>${panels('最近运行',runs.length?`<div class="activity-list">${runs.slice(0,4).map(run=>`<a class="activity-item" href="#run/${run.id}"><span class="activity-marker"></span><div><strong>${escape(projects.find(p=>p.id===run.project_id)?.name||'Project')}</strong><small>${stateNames[run.state]} · ${run.metrics.repair_count} 次修复</small></div><span class="activity-time">${time(run.created_at)}</span></a>`).join('')}</div>`:empty('还没有工程动态','运行后，这里将显示真实的执行状态。'))}</div></div>`+`<section class="panel"><div class="panel-heading"><h3>从需求到交付</h3><span class="muted">每一步，均可追溯</span></div><div class="pipeline" style="padding:24px">${['需求规划','契约定义','并行开发','审查验证','自动修复','集成交付'].map((label,i)=>`<span class="stage"><i>${String(i+1).padStart(2,'0')}</i>${label}</span>${i<5?'<b>→</b>':''}`).join('')}</div></section>`;}
function projectPage(project){const projectRuns=runs.filter(r=>r.project_id===project.id);const tabs=[['overview','概览'],['tasks','任务'],['contracts','契约'],['agents','Agents'],['runs','运行记录'],['git','Git'],['artifacts','产物'],['settings','设置']];return heading(project.name,project.description||'独立仓库 · 契约驱动 · 可验证交付',button('new-run',icon('plus')+' 新建运行',true),'PROJECT WORKSPACE')+tabBar(tabs)+`<div id="project-panel">${activeTab==='overview'?metrics([['工程运行',projectRuns.length,'所有历史运行','activity'],['已交付',projectRuns.filter(r=>r.state==='SUCCEEDED').length,'最终门禁通过','check'],['自动修复',projectRuns.reduce((n,r)=>n+r.metrics.repair_count,0),'累计修复尝试','branch'],['语言','Python','标准库工具链','code']])+panels('最近运行',runTable(projectRuns.slice(0,6))):'<div class="loading">加载项目数据…</div>'}</div>`;}
function tabBar(tabs){return `<div class="tabs" role="tablist">${tabs.map(([id,label])=>`<button class="tab ${activeTab===id?'active':''}" data-tab="${id}" role="tab" aria-selected="${activeTab===id}">${label}</button>`).join('')}</div>`;}
function taskTable(tasks){return tasks.length?`<div class="table-wrap"><table><thead><tr><th>任务</th><th>状态</th><th>依赖</th><th>修复</th><th>提交</th></tr></thead><tbody>${tasks.map(task=>`<tr class="clickable" data-task="${escape(task.id)}"><td><strong>${escape(task.spec.title)}</strong><div class="mono muted" style="margin-top:5px">${escape(task.spec_id)}</div></td><td>${badge(task.state)}</td><td>${escape(task.spec.dependencies.join(', ')||'无依赖')}</td><td>${task.attempt}</td><td class="mono">${short(task.commit)}</td></tr>`).join('')}</tbody></table></div>`:empty('等待任务规划','Planner 将根据需求生成结构化任务与依赖。');}
function agentCards(agents){return agents.length?`<div class="agent-grid">${agents.map(agent=>`<article class="agent-card">${badge(agent.state)}<h3>${escape(agent.role)}</h3><p class="mono">${escape(agent.model)}</p><div class="stats"><span>${agent.input_tokens+agent.output_tokens} tokens</span><span>${duration(agent.latency_ms)}</span></div><p style="margin-top:15px;margin-bottom:0">${escape(agent.task_id?.split(':').at(-1)||'全局规划')}</p></article>`).join('')}</div>`:empty('暂无 Agent 会话','开始运行后，这里显示实际的角色、模型与用量。');}
function artifactsTable(artifacts){return artifacts.length?`<div class="table-wrap"><table><thead><tr><th>产物</th><th>提交</th><th>创建时间</th><th></th></tr></thead><tbody>${artifacts.map(a=>`<tr><td class="mono">${a.id}</td><td class="mono">${short(a.commit)}</td><td>${time(a.created_at)}</td><td><a class="button small" href="/api/artifacts/${a.id}/download">下载 ZIP ↓</a></td></tr>`).join('')}</tbody></table></div>`:empty('还没有可交付产物','只有通过全部任务门禁与最终验证的运行，才能生成工程产物。');}
async function loadProjectTab(){const version=routeVersion,project=currentProject;if(!project||activeTab==='overview')return;const tab=activeTab;let html='';if(tab==='runs')html=panels('全部运行',runTable(runs.filter(r=>r.project_id===project.id)));else if(tab==='settings')html=panels('项目配置',`<dl class="detail-grid"><div><dt>执行模式</dt><dd>${project.provider==='fixture'?'确定性验收示例':'OpenAI-compatible'}</dd></div><div><dt>编程语言</dt><dd>Python</dd></div><div><dt>沙箱</dt><dd>${health.docker_available?'Docker CLI 已检测':'Docker 不可用 · 真实代码执行将阻止'}</dd></div><div><dt>模型配置</dt><dd>服务端环境变量 MASP_MODEL_BASE_URL / MASP_MODEL_NAME / MASP_MODEL_API_KEY</dd></div></dl>`);else if(tab==='git')html=panels('Git 仓库',`<dl class="detail-grid"><div><dt>托管仓库</dt><dd class="mono">${escape(project.repository)}</dd></div><div><dt>导入来源</dt><dd>${escape(project.source_repository||'在工作空间新建')}</dd></div><div><dt>集成策略</dt><dd>任务独立 worktree → 最终验证 → 快进合并</dd></div></dl>`);else{const data=await api(`/projects/${project.id}/${tab}`);if(tab==='tasks')html=panels('任务列表',taskTable(data));if(tab==='agents')html=agentCards(data);if(tab==='artifacts')html=panels('工程产物',artifactsTable(data));if(tab==='contracts')html=data.length?data.map(c=>panels(`Contract v${c.version} ${badge(c.validation)}`,`<dl class="detail-grid"><div><dt>兼容性</dt><dd>${c.potentially_breaking?'共享接口有变更，需审查':'无已知共享接口变更'}</dd></div><div><dt>契约摘要</dt><dd class="mono">${short(c.digest)}</dd></div><div><dt>注册时间</dt><dd>${time(c.created_at)}</dd></div></dl><pre class="code-block">${escape(JSON.stringify(c.plan.contracts,null,2))}</pre><details style="padding:0 22px 20px"><summary class="text-link">查看版本差异</summary><pre>${escape(JSON.stringify(c.diff,null,2))}</pre></details>`)).join(''):empty('暂无注册契约','Planner 完成规划后，系统将注册版本化共享契约。');}if(version===routeVersion&&activeTab===tab)$('#project-panel').innerHTML=html;}
function taskDetails(task){if(!task)return '';return `<div class="task-detail"><h3>${escape(task.spec.title)} ${badge(task.state)}</h3><p class="form-hint">${escape(task.spec.description)}</p><div class="mono muted">${escape(task.workspace||'等待分配工作区')}</div><pre>${escape(JSON.stringify({acceptance_criteria:task.spec.acceptance_criteria,allowed_paths:task.spec.allowed_paths,dependencies:task.spec.dependencies,commit:task.commit,error:task.error},null,2))}</pre>${task.diff?`<details><summary class="text-link">代码差异</summary><pre>${escape(task.diff)}</pre></details>`:''}</div>`;}
function graph(tasks){if(!tasks.length)return empty('正在规划任务','等待结构化计划与共享契约生成。');const ranks={};for(let n=0;n<tasks.length;n++)for(const task of tasks)if(task.spec.dependencies.every(dep=>dep in ranks))ranks[task.spec_id]=Math.max(-1,...task.spec.dependencies.map(dep=>ranks[dep]))+1;const levels=[...new Set(Object.values(ranks))].sort((a,b)=>a-b);return `<div class="graph">${levels.map(level=>`<div class="graph-column">${tasks.filter(t=>ranks[t.spec_id]===level).map(t=>`<button class="task-node ${t.state.toLowerCase()}" data-task="${escape(t.id)}"><div class="node-id">${escape(t.spec_id).toUpperCase()}</div><strong>${escape(t.spec.title)}</strong><div class="task-node-bottom">${badge(t.state)}<span>${t.attempt} 次修复</span></div><div class="mono muted" style="margin-top:9px">${t.spec.dependencies.length?'依赖 '+escape(t.spec.dependencies.join(', ')):'独立任务'}</div></button>`).join('')}</div>`).join('')}<div class="graph-column"><div class="task-node ${currentRun.state==='SUCCEEDED'?'succeeded':''}"><div class="node-id">FINAL GATE</div><strong>集成与最终验证</strong>${badge(currentRun.state==='SUCCEEDED'?'SUCCEEDED':currentRun.state==='FINAL_VERIFY'?'VERIFYING':'QUEUED')}</div></div></div>`;}
function verification(tasks,finalChecks){const entries=tasks.flatMap(task=>task.attempts.flatMap(attempt=>attempt.checks.map(c=>({...c,task:task.spec_id,attempt:attempt.attempt})))).concat(finalChecks.map(c=>({...c,task:'最终验证',attempt:0})));return entries.length?entries.map(check=>`<div class="event-row"><div>${badge(check.status)}</div><details><summary>${escape(check.task)} / ${escape(check.name)} · 第 ${check.attempt+1} 次 · ${duration(check.duration_ms)}</summary><pre>${escape(check.command.join(' '))}\n\n${escape(check.stdout)}${escape(check.stderr)}</pre></details></div>`).join(''):empty('暂无执行证据','审查通过后，验证引擎将运行已声明的检查。');}
function eventsHtml(){return liveEvents.length?liveEvents.slice(-100).reverse().map(event=>`<div class="event-row"><time>${new Date(event.timestamp).toLocaleTimeString('zh-CN')}</time><details><summary>${escape(event.type)} <span class="muted">${escape(event.task_id?.split(':').at(-1)||'')}</span></summary><pre>${escape(JSON.stringify(event.payload,null,2))}</pre></details></div>`).join(''):empty('等待运行事件','运行中的事件将实时出现在这里。');}
function runBody(){const run=currentRun,tasks=run.tasks;switch(activeTab){case 'workflow':return panels('任务依赖图 <span class="count">'+tasks.length+'</span>',graph(tasks)+taskDetails(tasks.find(t=>t.id===selectedTask)),`<span class="muted">最大并发 ${run.request.max_agents} · 独立 Git worktree</span>`)+panels('验证摘要',verification(tasks,run.final_checks));case 'tasks':return panels('任务执行',taskTable(tasks)+taskDetails(tasks.find(t=>t.id===selectedTask)));case 'agents':return agentCards(run.agents);case 'events':return panels('实时事件 <span class="count">'+liveEvents.length+'</span>',eventsHtml(),'<span class="muted">按事件序号记录 · 支持历史查看</span>');case 'diff':return panels('Git diff',`<pre class="code-block">${escape(run.diff||tasks.map(t=>t.diff).filter(Boolean).join('\n')||'暂未产生代码差异')}</pre>`);case 'review':return panels('结构化审查',tasks.length?tasks.map(task=>`<div class="task-detail"><h3>${escape(task.spec.title)}</h3>${task.findings.length?`<pre>${escape(JSON.stringify(task.findings,null,2))}</pre>`:`<p class="form-hint">${task.attempts.length?'没有阻塞问题；验收仍取决于可执行验证。':'等待审查'}</p>`}</div>`).join(''):empty('暂无审查结果','Reviewer 将依据契约和代码输出结构化问题。'));case 'tests':return panels('验证与修复记录',verification(tasks,run.final_checks));default:return '';}}
function runPage(){const run=currentRun,finished=terminal.has(run.state),project=projects.find(p=>p.id===run.project_id);const actions=finished?button('retry','重新运行')+(run.artifact_id?`<a class="button primary" href="/api/artifacts/${run.artifact_id}/download">下载工程产物 ↓</a>`:''):button(run.control==='paused'?'resume':'pause',run.control==='paused'?'继续运行':'暂停调度')+button('cancel','取消运行',false,'class="danger"');return heading(project?.name||'工程运行',run.request.requirement,actions,'RUN / '+run.id)+`<div style="margin-top:-16px;margin-bottom:22px">${badge(run.display_state)} <span class="mono muted" style="margin-left:12px">${short(run.repository_revision)} → ${short(run.commit)}</span></div>`+(run.error?`<div class="error-box">${escape(run.error)}</div>`:'')+metrics([['已完成任务',`${run.tasks.filter(t=>t.state==='SUCCEEDED').length} / ${run.tasks.length}`,'已通过任务门禁','check'],['执行耗时',duration(run.metrics.duration_ms),finished?'运行已结束':'结束后汇总','clock'],['自动修复',run.metrics.repair_count,'修复尝试总数','branch'],['模型用量',run.agents.reduce((n,a)=>n+a.input_tokens+a.output_tokens,0),'tokens · 费用未配置','agent']])+tabBar([['workflow','工作流'],['tasks','任务'],['agents','Agents'],['events','事件 / 日志'],['diff','代码差异'],['review','审查'],['tests','验证']])+`<div id="run-panel">${runBody()}</div>`;}
async function route(){const version=++routeVersion;eventSource?.close();eventSource=null;clearTimeout(refreshTimer);const [page,id]=location.hash.slice(1).split('/');currentProject=null;currentRun=null;selectedTask=null;const section=page||'dashboard';document.querySelectorAll('[data-nav]').forEach(el=>el.classList.toggle('active',el.dataset.nav===(section==='project'?'projects':section==='run'?'runs':section)));$('#breadcrumb').textContent=({dashboard:'总览',projects:'项目',project:'项目空间',runs:'运行记录',run:'工程运行',artifacts:'工程产物'})[section]||'总览';try{[projects,runs,health]=await Promise.all([api('/projects'),api('/runs'),api('/health')]);if(version!==routeVersion)return;$('#project-count').textContent=projects.length;$('#recent-projects').innerHTML=projects.slice(0,5).map(p=>`<a href="#project/${p.id}">${escape(p.name)}</a>`).join('');if(section==='project'){currentProject=projects.find(p=>p.id===id);if(!currentProject)throw Error('项目不存在');activeTab='overview';$('#content').innerHTML=projectPage(currentProject);}else if(section==='run'){currentRun=await api('/runs/'+id);liveEvents=await api(`/runs/${id}/events`);if(version!==routeVersion)return;activeTab='workflow';$('#content').innerHTML=runPage();connectEvents(id,version);}else if(section==='projects'){$('#content').innerHTML=heading('项目','所有工程项目，都有独立的代码与执行历史。',button('new-project',icon('plus')+' 创建项目',true),'PROJECTS')+panels('项目列表',projects.length?projectRows(projects):empty('暂无项目','创建项目，开始一次可追溯的工程运行。'),'<input class="search-input" id="project-search" aria-label="搜索项目" placeholder="搜索项目…">');}else if(section==='runs')$('#content').innerHTML=heading('运行记录','查看每次工程运行的状态、验证结果与修复过程。','','RUN HISTORY')+panels('全部运行',runTable(runs));else if(section==='artifacts'){const all=await Promise.all(projects.map(p=>api(`/projects/${p.id}/artifacts`)));if(version!==routeVersion)return;$('#content').innerHTML=heading('工程产物','通过最终验证的代码快照，可下载、可追溯。','','ARTIFACTS')+panels('可交付产物',artifactsTable(all.flat()));}else $('#content').innerHTML=dashboard();}catch(error){$('#content').innerHTML=`<div class="error-box">${escape(error.message)}</div>${button('reload','重新连接')}`;}}
function connectEvents(id,version){eventSource=new EventSource(`/api/runs/${id}/stream?after=${liveEvents.at(-1)?.sequence||0}`);eventSource.onmessage=event=>{if(version!==routeVersion)return;liveEvents.push(JSON.parse(event.data));clearTimeout(refreshTimer);refreshTimer=setTimeout(async()=>{try{const run=await api('/runs/'+id);if(version!==routeVersion)return;currentRun=run;$('#content').innerHTML=runPage();}catch(error){toast(error.message);}},150);};eventSource.addEventListener('complete',()=>eventSource?.close());}
function openProject(){const form=$('#project-form');form.reset();form.querySelector('.form-error').textContent='';$('#repo-label').hidden=true;$('#project-dialog').showModal();}
function openRun(project){currentProject=project;const form=$('#run-form');form.reset();form.querySelector('.form-error').textContent='';if(project.provider==='fixture')form.elements.requirement.value='构建包含加法与减法模块的 Python 算术库，覆盖正数、负数和零值，并通过最终集成验证。';$('#run-mode-hint').textContent=project.provider==='fixture'?'当前为固定算术验收示例，需求文本用于运行记录。实际产品需求请使用真实模型模式。':'将使用服务端配置的模型规划和开发；所有生成代码检查均在 Docker 沙箱执行。';$('#run-dialog').showModal();}
document.addEventListener('click',async event=>{const tab=event.target.closest('[data-tab]');if(tab){activeTab=tab.dataset.tab;try{if(currentRun){$('#content').innerHTML=runPage();}else if(currentProject){$('#content').innerHTML=projectPage(currentProject);await loadProjectTab();}}catch(error){toast(error.message);}return;}const task=event.target.closest('[data-task]');if(task){if(currentRun){selectedTask=task.dataset.task;$('#run-panel').innerHTML=runBody();}else{const data=await api('/tasks/'+encodeURIComponent(task.dataset.task));location.hash='run/'+data.run_id;}return;}const link=event.target.closest('[data-route]');if(link){location.hash=link.dataset.route;return;}const action=event.target.closest('[data-action]');if(!action)return;try{switch(action.dataset.action){case 'new-project':openProject();break;case 'close-dialog':action.closest('dialog').close();break;case 'new-run':openRun(currentProject);break;case 'reload':await route();break;case 'demo':{action.disabled=true;const p=await api('/projects',{name:'calculator-'+Date.now().toString().slice(-5),description:'双 Agent 并行 + 故障注入 + 自动修复验收',provider:'fixture'});const r=await api(`/projects/${p.id}/runs`,{requirement:'构建加法与减法模块，执行故障注入并修复，通过最终算术集成测试。',inject_failure:true,max_agents:2});location.hash='run/'+r.id;break;}default:if(currentRun&&['pause','resume','cancel','retry'].includes(action.dataset.action)){action.disabled=true;const result=await api(`/runs/${currentRun.id}/${action.dataset.action}`,{});if(action.dataset.action==='retry')location.hash='run/'+result.id;else{currentRun=await api('/runs/'+currentRun.id);$('#content').innerHTML=runPage();toast('操作已记录');}}}}catch(error){toast(error.message);}finally{action.disabled=false;}});
$('#project-form').addEventListener('change',event=>{if(event.target.name==='source'){$('#repo-label').hidden=event.target.value!=='import';$('#project-form').elements.repository.required=event.target.value==='import';}});
$('#project-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,submit=form.querySelector('[type=submit]');submit.disabled=true;try{const fields=new FormData(form);const project=await api('/projects',{name:fields.get('name'),description:fields.get('description'),provider:fields.get('provider'),repository:fields.get('source')==='import'?fields.get('repository'):null});$('#project-dialog').close();location.hash='project/'+project.id;}catch(error){form.querySelector('.form-error').textContent=error.message;}finally{submit.disabled=false;}});
$('#run-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,submit=form.querySelector('[type=submit]');submit.disabled=true;try{const fields=new FormData(form);const run=await api(`/projects/${currentProject.id}/runs`,{requirement:fields.get('requirement'),max_agents:Number(fields.get('max_agents')),max_retries:Number(fields.get('max_retries')),inject_failure:fields.has('inject_failure'),approve_contract_change:fields.has('approve_contract_change')});$('#run-dialog').close();location.hash='run/'+run.id;}catch(error){form.querySelector('.form-error').textContent=error.message;}finally{submit.disabled=false;}});
document.addEventListener('input',event=>{if(event.target.id==='project-search'){const list=projects.filter(p=>p.name.toLowerCase().includes(event.target.value.toLowerCase()));document.querySelector('.panel .project-row')?.parentElement.querySelectorAll('.project-row').forEach(row=>row.remove());const panel=$('.panel');panel.querySelector('.empty')?.remove();panel.insertAdjacentHTML('beforeend',list.length?projectRows(list):empty('没有匹配的项目','尝试其他项目名称。'));}});
window.addEventListener('hashchange',route);
route();
